### ISSUE TITLE
xml to json

### ISSUE THREAD

**Issue by kikillotest** [nmarus/node-ews#28] opened 2016-11-09 16:36 UTC
hey guys,
i can't figure how to write the body attribtue in this soap request (https://msdn.microsoft.com/en-us/library/office/aa566468(v=exchg.150).aspx) to json.
 i tried different solutions as : 
    'Body' : {
        'Attributes' : {
          'BodyType' : 'Text'
        },
        'Body' : 'Hello !'
      }
but i keep getting this error : 
WSDL.prototype.findChildSchemaObject = function(parameterTypeObj, childName) {
RangeError: Maximum call stack size exceeded
    at WSDL.findChildSchemaObject (/srv/node/odj/node_modules/soap/lib/wsdl.js:1902:48)
...

any idea how to write that body correctly ?

thanks

**Comment by nmarus** [comment] 2016-11-25 02:58
This is a duplicate of issue #17

**Closed by nmarus** 2016-11-25 02:58 UTC
Labels: duplicate
